---

- name: Publish The Beanstalkd Check
  copy:
    src="checks.d/beanstalkd.py"
    dest="/etc/dd-agent/checks.d"
    owner="{{ datadog_user }}"
    group="{{ datadog_group }}"
    mode="0644"

- name: Install The Beanstalkc Python Client
  command: /opt/datadog-agent/embedded/bin/pip install beanstalkc
  notify: restart datadog-agent
